### PR TITLE
Added Loader to the UI when the API calls are being made

### PR DESCRIPTION
**Pull request by nameerakhter**
This PR addresses issue #7 

Added a loading.tsx file which displays the loader when making API call (video attached):
https://github.com/user-attachments/assets/1d896699-5c3d-41dd-8d62-0bf7c36c5624

Additional changes: Also updated the variants of toast messages that is being displayed + updated the verifyEmail UI to match the rest of the forms 

Screenshot 2024-12-07 214551

image

### CODE REVIEW

**Comment by poswalsameer** [comment]
> This PR addresses issue #7
> 
> Added a loading.tsx file which displays the loader when making API call (video attached): https://github.com/user-attachments/assets/1d896699-5c3d-41dd-8d62-0bf7c36c5624
> 
> Additional changes: Also updated the variants of toast messages that is being displayed + updated the verifyEmail UI to match the rest of the forms
> 
> Screenshot 2024-12-07 214551
> 
> image

Thanks for working on this. Can you please you a minimal loading icon for this, orange and blue combination is not looking that good. Basic blue or white loader would work here ig.

**Comment by nameerakhter** [comment]
@poswalsameer here is the updated loader let me known if you there are any more changes

Screenshot (33)

**Comment by poswalsameer** [comment]
> @poswalsameer here is the updated loader let me known if you there are any more changes
> 
> Screenshot (33)

Looks alright for now. Will merge this. 

One small tip: When you are contributing to any repository next time, make sure you don't raise PR directly in the `main`/`master` branch. Create a new specific branch for that fix/feature and push your changes to that branch only. So, the reviewer/maintainer can review that branch only and the main does not gets affected at all.

**Comment by nameerakhter** [comment]
> > @poswalsameer here is the updated loader let me known if you there are any more changes
> > Screenshot (33)
> 
> Looks alright for now. Will merge this.
> 
> One small tip: When you are contributing to any repository next time, make sure you don't raise PR directly in the `main`/`master` branch. Create a new specific branch for that fix/feature and push your changes to that branch only. So, the reviewer/maintainer can review that branch only and the main does not gets affected at all.

I was supposed to that but I somehow overlooked it that's my bad. Surely will keep that in mind. Thankyou 😊

**Pull request merged**
